Example notebook to show how modul integration works. 
Start with getting an image tensor with 1 x Width x Height x 3 dimensions.

In [8]:
import car_damage
import tensorflow as tf
import numpy as np
from PIL import Image

# Option 1: Read from file path with tf.io
image1 = tf.io.read_file('./example_image.jpg')
image1 = tf.io.decode_jpeg(image1, channels=3)

# Option 2: Convert from an already existing array.
image2 = Image.open('./example_image.jpg')
image2 = np.asarray(image2)
image2 = tf.convert_to_tensor(image2)

Comparing both arrays you can see that PIL and TensorFlow load the same image with slightly different rbg values. 
We will see later if it has influence on the results.

In [9]:
print(image1)
print(image2)

tf.Tensor(
[[[150 150 142]
  [150 150 142]
  [150 150 142]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[149 149 141]
  [149 149 141]
  [149 149 141]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[147 147 139]
  [147 147 139]
  [147 147 139]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[201 191 166]
  [202 191 169]
  [187 179 158]
  ...
  [ 77  74  65]
  [105 102  93]
  [132 129 120]]

 [[218 208 183]
  [215 204 182]
  [195 187 166]
  ...
  [ 82  79  70]
  [109 106  97]
  [135 132 123]]

 [[223 213 188]
  [218 207 185]
  [195 187 166]
  ...
  [ 85  82  73]
  [112 109 100]
  [137 134 125]]], shape=(1024, 1024, 3), dtype=uint8)
tf.Tensor(
[[[151 150 145]
  [151 150 145]
  [150 149 144]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[149 148 143]
  [149 148 143]
  [149 148 143]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[148 147 142]
  [148 147 142]
  [148 147 142]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]


In [ ]:
You need to initizalise the application configs with a json file. Initialisation will take a while, since it also runs one image inference for ressource allocation.

In [13]:
car_damage.init('./application_config.json')

In [14]:
result1 = car_damage.run_classification(image1)
print(result1)
result2 = car_damage.run_classification(image2)
print(result2)

{'damage': [('moderate', 0.98487824)], 'location': [('front', 0.94939476)], 'damagetype': []}
